### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by The-Compiler** [meejah/cuvner#1]
It seems cuvner doesn't have Python 3 support:

```
Traceback (most recent call last):
  File "./.venv/bin/cuv", line 9, in <module>
    load_entry_point('cuvner==0.0.0', 'console_scripts', 'cuv')()
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/site-packages/cuv/cli.py", line 139, in graph
    graph_coverage(keyword, cfg)
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/site-packages/cuv/graph.py", line 97, in graph_coverage
    graph += percent_to_bar(float(bad) / float(total))
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/site-packages/cuv/graph.py", line 70, in percent_to_bar
    unichr(0x2580 + int(prct / 0.125)), fg='red', bg='green'
NameError: name 'unichr' is not defined
```

But when running it in a Python2 virtualenv, I can't run it over my Python3 source either:

```
Coverage in: /home/florian/proj/qutebrowser/git/qutebrowser/
Traceback (most recent call last):
  File "./.venv2/bin/cuv", line 9, in <module>
    load_entry_point('cuvner==0.0.0', 'console_scripts', 'cuv')()
  File "/home/florian/proj/qutebrowser/git/.venv2/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/florian/proj/qutebrowser/git/.venv2/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/florian/proj/qutebrowser/git/.venv2/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/florian/proj/qutebrowser/git/.venv2/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/florian/proj/qutebrowser/git/.venv2/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/florian/proj/qutebrowser/git/.venv2/lib/python2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/florian/proj/qutebrowser/git/.venv2/lib/python2.7/site-packages/cuv/cli.py", line 139, in graph
    graph_coverage(keyword, cfg)
  File "/home/florian/proj/qutebrowser/git/.venv2/lib/python2.7/site-packages/cuv/graph.py", line 76, in graph_coverage
    data = create_analysis(cfg.data, fname)
  File "/home/florian/proj/qutebrowser/git/.venv2/lib/python2.7/site-packages/cuv/analysis.py", line 34, in create_analysis
    args = covdata.analysis2(name)
  File "/home/florian/proj/qutebrowser/git/.venv2/lib/python2.7/site-packages/coverage/control.py", line 872, in analysis2
    analysis = self._analyze(morf)
  File "/home/florian/proj/qutebrowser/git/.venv2/lib/python2.7/site-packages/coverage/control.py", line 891, in _analyze
    return Analysis(self.data, it)
  File "/home/florian/proj/qutebrowser/git/.venv2/lib/python2.7/site-packages/coverage/results.py", line 19, in __init__
    self.statements = self.file_reporter.lines()
  File "/home/florian/proj/qutebrowser/git/.venv2/lib/python2.7/site-packages/coverage/python.py", line 139, in lines
    self._statements, self._excluded = self.parser.parse_source()
  File "/home/florian/proj/qutebrowser/git/.venv2/lib/python2.7/site-packages/coverage/parser.py", line 207, in parse_source
    self._raw_parse()
  File "/home/florian/proj/qutebrowser/git/.venv2/lib/python2.7/site-packages/coverage/parser.py", line 165, in _raw_parse
    self.statement_starts.update(self.byte_parser._find_statements())
  File "/home/florian/proj/qutebrowser/git/.venv2/lib/python2.7/site-packages/coverage/parser.py", line 73, in byte_parser
    self._byte_parser = ByteParser(self.text, filename=self.filename)
  File "/home/florian/proj/qutebrowser/git/.venv2/lib/python2.7/site-packages/coverage/parser.py", line 342, in __init__
    filename, synerr.msg, synerr.lineno
coverage.misc.NotPython: Couldn't parse '/home/florian/proj/qutebrowser/git/qutebrowser/app.py' as Python source: 'invalid syntax' at line 767
```

**Comment by meejah** [comment]
I fixed all the `unichr`s that were's `six.unichr` bt haven't yet actually tested on Python3 ;)

**Comment by meejah** [comment]
With the latest commit, it works in python3 for me -- I didn't have any `.coverage` files produced via Python3 handy, so I didn't try that yet.

Leaving open until I do, or @The-Compiler confirms their problem is solved :)

**Comment by The-Compiler** [comment]
Thank you! `cuv graph` works fine now (and looks awesome!), but `cuv hist` doesn't:

```
Traceback (most recent call last):
  File "./.venv/bin/cuv", line 9, in <module>
    load_entry_point('cuvner==0.0.0', 'console_scripts', 'cuv')()
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/site-packages/cuv/cli.py", line 258, in hist
    histogram_coverage(keyword, cfg)
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/site-packages/cuv/histogram.py", line 82, in histogram_coverage
    coverage_data.sort(lambda a, b: cmp(a[1].numbers.n_statements, b[1].numbers.n_statements))
TypeError: must use keyword argument for key function
```

and neither does `cuv pixel`:

```
Traceback (most recent call last):
  File "./.venv/bin/cuv", line 9, in <module>
    load_entry_point('cuvner==0.0.0', 'console_scripts', 'cuv')()
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/site-packages/cuv/cli.py", line 171, in pixel
    pixel_vis(cfg, pixel_size, height, show)
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/site-packages/cuv/pixel.py", line 215, in pixel_vis
    highlight(open(fname, 'r').read(), get_lexer_by_name('python'), formatter=frmt)
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/site-packages/pygments/__init__.py", line 87, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/site-packages/pygments/__init__.py", line 66, in format
    formatter.format(tokens, realoutfile)
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/site-packages/cuv/pixel.py", line 143, in format
    text = unicode(value)
NameError: name 'unicode' is not defined
```

**Comment by meejah** [comment]
Thanks :) Those should both work now.

Note that "cuv hist" still has a problem with the labels. I can't figure out a good way to place the text so it lines up properly :/

**Comment by The-Compiler** [comment]
Yeah, works now! :smile: It reports far less coverage than I'd expect though (46% instead of 75%), and I think I'm looking at the combined `.coverage`. I'll investigate what's going on.

**Comment by meejah** [comment]
Great :)

Beware that it's "magically" finding the .coverage file unless you specifiy `--coverage` (the magic is: keep going to higher directories until we find a .coverage). See the "note on Tox" in the README if you've got multiple .coverage files in subdirectories etc...

**Comment by meejah** [comment]
Okay, I made a bunch of chages, upgrading to use `click.echo` basically everywhere, with `color=True` so that I don't need if/else blocks to handle Python2 versus Python3's crazy notions of unicode-ness. 

So, should be fixed...
